# Generated by Django 5.0.6 on 2024-07-25 03:59

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(null=True, upload_to=user_profile.models.profile_path)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
