# Generated by Django 5.0.6 on 2024-08-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=50)),
                ('comments', models.ManyToManyField(to='comment.comment')),
            ],
        ),
    ]
