# Generated by Django 5.0.6 on 2024-07-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
