# Generated by Django 5.0.6 on 2024-07-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likers',
        ),
    ]
