# Generated by Django 5.0.6 on 2024-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_post_comment_author_and_more'),
        ('post', '0004_rename_likes_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='comment.comment'),
        ),
    ]
