# Generated by Django 5.0.6 on 2024-07-25 00:33

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to=user.models.construct_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
