# Generated by Django 5.0.6 on 2024-08-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='descriptiob',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
