# Generated by Django 5.0.6 on 2024-07-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_setup_complete_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='account_status',
        ),
    ]
