# Generated by Django 5.0.6 on 2024-08-17 00:22

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=comment.models.construct_path)),
                ('text', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
