# Generated by Django 5.0.6 on 2024-08-05 03:38

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to=comment.models.construct_path),
        ),
    ]
