# Generated by Django 5.0.6 on 2024-08-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('share', 'share')], max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
